### ISSUE TITLE
Code Protection

### ISSUE THREAD

**Issue by garudaonekh** [pulkin/micropython#110]
Hi,
I want to protect the code. I see many people suggest to compile the Python code into the library and use the main.py to call the code.

But I don't know how to do this low level compilation,.

Thanks for your suggestion.

Regards;

**Comment by pulkin** [comment]
https://docs.micropython.org/en/latest/reference/mpyfiles.html

**Comment by garudaonekh** [comment]
Thanks, it worked. But main.mpy not executed so I need to use a main.py and call my main file as module
