### ISSUE TITLE
accidentally disable REPL

### ISSUE THREAD

**Issue by garudaonekh** [pulkin/micropython#113]
HI,
I accidentally put in main.py and my code to reverse back not called. uos.dupterm(None, 1)

I run CoolWatch to reflash the A9 module but the main.py is still there. Anyway, to restore it back?

thanks;

**Comment by pulkin** [comment]
[You could comment this line out](https://github.com/pulkin/micropython/blob/c274c947c611f510fd2b1c4ef6cbd9f4283794fc/ports/gprs_a9/main.c#L189)

**Comment by garudaonekh** [comment]
thank you very much
