### ISSUE TITLE
Network Status return 17

### ISSUE THREAD

**Issue by garudaonekh** [pulkin/micropython#114]
HI,
what does the 17 means from on_status_event()  and from get_network_status() function?
I can't find document for that.

Normally, I received 1 for ok, and 4 for not connected from the cell tower.

Please share me list of this number, thanks

**Comment by pulkin** [comment]
https://github.com/pulkin/micropython/blob/c274c947c611f510fd2b1c4ef6cbd9f4283794fc/ports/gprs_a9/modcellular.c#L53-L60

17 sounds like a normal status to me
