### ISSUE TITLE
socket.socket().setblocking(True) NotImpletedError

### ISSUE THREAD

**Issue by 2niuhe** [pulkin/micropython#24]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NotImplementedError: Not implemented yet

**Comment by pulkin** [comment]
This should be possible to implement: `lwip_setsockopts`, however, some constants are missing.

**Comment by pulkin** [comment]
Dunno if it actually works (either it is always blocking or I download stuff in my tests too fast).
