### ISSUE TITLE
Fix `ussl` and `uhashlib`

### ISSUE THREAD

**Issue by pulkin** [pulkin/micropython#32]
Resolve issues with the build system and move `MICROPY_*` variables from the `Makefile` back to `mpconfigport.h`. Enable `uhashlib` which causes build failures at this point.

**Comment by pulkin** [comment]
The problem might be in `extmod/moduhashlib.c` which does not pick `MICROPY_SSL_*` variables and re-compiles stuff causing duplicate symbols.

**Comment by pulkin** [comment]
@sebi5361, please check whether `ssl`, `hashlib`, `cryptolib` work for you. You may build from `uhashlib` or just download [these builds](https://dev.azure.com/gpulkin/micropython/_build/results?buildId=142&view=artifacts&type=publishedArtifacts).

**Comment by sebi5361** [comment]
I was able to `import ssl`, `hashlib`, and `cryptolib` properly.
I was able to synchronise my local project folder with the board (for the most part) which involves using `hashlib`.
Thank you!

**Comment by sebi5361** [comment]
Dear Pulkin,
Soon, will you merge branches *binary-patches* and *uhashlib* so I can benefit from both fixes together?

**Comment by pulkin** [comment]
Sure, I just need to test both on my hardware.

**Comment by pulkin** [comment]
Merged.

**Comment by sebi5361** [comment]
Thanks
