### ISSUE TITLE
Rebooting the board with Ctrl-D doesn't clear the watchdog

### ISSUE THREAD

**Issue by sebi5361** [pulkin/micropython#37]
I have noticed that when rebooting the board with `Ctrl-D` the watchdog remains on (if set before).
It might be the same with `machine.reset()`.

If I remember well, this was also the case on some other MicroPython ports but got fixed.

**Comment by pulkin** [comment]
A more general question is: how "soft" should soft reset be? Should it

[ ] reset cellular connectivity (disconnect from GPRS, etc)
[ ] reset power setup (remove watchdog, disable GPIOs, disable gps, reset minimal frequency)
[ ] reset time

maybe more?

**Comment by sebi5361** [comment]
I believe "soft" should be the same as when powering the board on.
Your list seems exhaustive. I don't think we are missing anything.

I am not that sure, but it seems the reset button is not hard wired to resetting the board.
I say this because it needs to be pressed and release, and in the debugger some kind of error show up at that time. Maybe there is a way to trigger the very same process with the soft reset?

**Comment by pulkin** [comment]
Ok, I think it is a good first bug to fix for you or anyone else willing to contribute. What you need to do is:

1. Ensure it is convention (i.e. hardware watchdog is shut down on software reset for mp running on ESP8266/32/any other mainstream board);
2. Go to file `modmachine.c` and put `modmachine_watchdog_off` into `modmachine_init0`;
3. Put the declaration of `modmachine_watchdog_off` before `modmachine_init0`;
4. Build it and test if it works on the board;
5. PR here.

**Comment by sebi5361** [comment]
😎
