### ISSUE TITLE
Example on how to automatically connect to the APN

### ISSUE THREAD

**Issue by sebi5361** [pulkin/micropython#38]
Could you provide an example on how to automatically connect to the APN when booting?
I implemented a loop but often it just won't connect forever.

**Comment by pulkin** [comment]
You may try something like:
```python
import cellular
import time
timeout = time.ticks_ms() + 1e4
while time.ticks_ms() < timeout:
    try:
        cellular.gprs("apn", "user", "pass")
        break;
    except CellularError:
        if time.ticks_ms() < timeout:
            time.sleep(1)
        else:
            raise
```

**Comment by pulkin** [comment]
I added a callback `on_status_event(f)` for your convenience. The function you input will be triggered each time the network status changed. You may invent something like
```python
def f(status):
    if status == 1:
        cellular.gprs("apn", "user", "pass")
    cellular.on_status_event(None)
cellular.on_status_event(f)
```
and it will *hopefully* work.

**Comment by pulkin** [comment]
MWE https://github.com/pulkin/micropython/blob/master/ports/gprs_a9/examples/example_42_event_driven_gprs.py

**Comment by pulkin** [comment]
Feel free to reopen.
