### ISSUE TITLE
mmc sd card ?

### ISSUE THREAD

**Issue by ens4dz** [pulkin/micropython#52]
First, thanks a lot for this port.
i have a newbie question: Is possible to log gps data to sdcard ?

**Comment by pulkin** [comment]
I did not try it but they claim it is possible. It should be mounted automatically. Afterwards you just ... log the data into some file or whatever.

**Comment by ens4dz** [comment]
after search finnaly I found sdcard mounted  under /t 
it read 16 GB FAT32 memory normaly
### M:\2020\A9G\openCellDb>ampy --port com10 ls /t
/t/log
/t/log_34CE00B3BED8_s.txt
/t/media
/t/record
/t/time_lapse
source:
https://ai-thinker-open.github.io/GPRS_C_SDK_DOC/en/c-sdk/function-api/file-system.html

**Comment by arlucio** [comment]
This can definitely be closed, it's just always mounted on /t, and you can manipulate files on it as you would normally do on other directories.
