### ISSUE TITLE
Error in umqtt after last commit

### ISSUE THREAD

**Issue by parafagus** [pulkin/micropython#57]
Hi.
I have an error "OSError: [Errno 5] EIO" after the last commit.
But after return to the previous version all is Ok.
In this code:
client = simple.MQTTClient(v_user, 'my_url.com', port=8883, user=v_user, password=v_pass, ssl=True)
client.connect()

**Comment by pulkin** [comment]
I cannot reproduce it with the latest commit. Please provide more information.
