### ISSUE TITLE
USSD

### ISSUE THREAD

**Issue by ens4dz** [pulkin/micropython#59]
First thanks a lot for this project,
I am newbie, any help to add USSD request ?
thanks.

**Comment by pulkin** [comment]
Yep, it looks relatively easy as presented in demos

https://github.com/Ai-Thinker-Open/GPRS_C_SDK/blob/8d4426f32df699594f42abeddb99f43c82d36f45/demo/ussd/src/demo_ussd.c#L121-L140

**Comment by pulkin** [comment]
Here you go with the [example](https://github.com/pulkin/micropython/blob/master/ports/gprs_a9/examples/example_43_ussd.py).

**Comment by ens4dz** [comment]
My problem has been solved,
Thank your for the support.
