### ISSUE TITLE
Need clear instructions on flashing the firmware

### ISSUE THREAD

**Issue by orkunkilinc** [pulkin/micropython#95]
Hi everyone,

I have been trying to flash micropython to my newly arrived A9G boards. Since AI thinker wiki went dark, I could only get my hands on CSDTK4.2 binaries and used Coolwatcher to flash. 

But using firmware_debug_flash.lod and firmware_debug_full from the releases page, it gives me;

> Fastpf V2 over Host
> Loading the lod files: 
> firmware_debug_full.lod
> Using flash programmer: 
> firmware_debug_flash.lod
> Ramrunning the flash programmer...
> 
> Resetting SPI flash...
> Done.
> 
> Entered Host Monitor mode.
> 
> No boot sector struct exists. Skipping ...
> 
> Event sniffer (re)starting. (Connection: Event Sniffer (COM42))
> 
> ￼ `dofastpfXfer': The flash programmer has not sent his READY event! (FastPf::FlashProgrammerNotReady)

With every documentation and tool being gone with the wiki and not being able to get this simple thing to work is really frustrating. What am I doing wrong?

Thank You

**Comment by ens4dz** [comment]
You are using  a wrong flasher file, log must be something like:
```
Using flash programmer:
host_8955_flsh_spi32m_ramrun.lod
```
Thanks to Wayback service, You can browse wiki:
https://web.archive.org/web/20201018074025/https://ai-thinker-open.github.io/GPRS_C_SDK_DOC/en/c-sdk/burn-debug.html
