### ISSUE TITLE
SMS Error object has no attribute 'SMS_RECEIVED'

### ISSUE THREAD

**Issue by marcosasilvalepe** [pulkin/micropython#96]
Hi! I've been trying to read SMS using example_41_sms.py but when the SMS is received I get the following error:

Traceback (most recent call last):
  File "/t/main.py", line 16, in sms_handler
AttributeError: 'module' object has no attribute 'SMS_RECEIVED'

Has anyone had this problem ?

**Comment by pulkin** [comment]
That example might be outdated since e7bfbb23e4f86d6d9dd05776cda569ba0d7aa275.

**Comment by marcosasilvalepe** [comment]
OK, got it!

Doing `else` insead of `elif` solved it. Thanks.

**Comment by Dracoit** [comment]
Thanks marcosasilvalepe,

After the fix, I still received a warning as follows: "Warning: Failed to poll all SMS: the list may be incomplete"  when issued the command ->  cellular.SMS.list().
as I can see from the output there was some SMS shown as None: Samp: [ "Msg 1",  "Msg 2", ..., None, None..]
but after every call of the function, the msg starts appearing and the None is no more visible.
Now it shows no error. 

just a fix for the warning that I was facing.

**Comment by iotmj** [comment]
Hi Dracoit, how you fix the above , i also get warning failed to poll all sms, list may incomplete. after this 'none'. i executed                   
 else:    
        print("SMS received, attempting to read ...")
        ls = cellular.SMS.list()
        print(ls[-1])
        flag = 0
