### ISSUE TITLE
machine.set_idle() argument

### ISSUE THREAD

**Issue by marcosasilvalepe** [pulkin/micropython#98]
Hi! I tried to put the module to sleep using `machine.idle() ` but it throws "the object has no attribute idle" error. 

Checking the attributes of machine, the method listed is `machine.set_idle()`. It takes an argument but no idea the type of argument it should be.

Supplying an int or boolean doesn't throw any errors.

Are there any examples on how to use this method and checking the status of cpu frequency being used ?

**Comment by bokolob** [comment]
It’s true/false argument - to enable/disable idle mode respectively

**Comment by marcosasilvalepe** [comment]
Thanks!!
